version: '2.1'
services:
    node:
          image: akshat7593/testapi_node
          env_file:
            - ./.env
          ports:
            - "${WEB_PORT}:${WEB_PORT}"
          depends_on:
            db:
              condition: service_healthy
                
          
    db:
          image: akshat7593/testapi_db
          ports:
            - "3306:3306"
          env_file:
          - ./.env
          # environment:
          #   MYSQL_USER: root
          #   MYSQL_PASSWORD: Aks@253854
          healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_PASSWORD
